CREATE TABLE jobs (
    empregoID INT AUTO_INCREMENT PRIMARY KEY,
    empresaID INT NOT NULL,
    empresaNome VARCHAR(255) NOT NULL,
    imgEmpresa VARCHAR(500),
    qtdFuncionario INT,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    area VARCHAR(100) NOT NULL,
    nivel ENUM('Júnior', 'Pleno', 'Sênior', 'Especialista', 'Estágio'),
    tipoContrato ENUM('CLT', 'PJ', 'Estágio', 'Temporário') NOT NULL,
    tipoTrabalho ENUM('Remoto', 'Presencial', 'Híbrido') NOT NULL,
    cargaHoraria VARCHAR(50),
    mediaSalario DECIMAL(10, 2),
    localizacao VARCHAR(255) NOT NULL,
    requisitos JSON,
    diferenciais JSON,
    beneficios JSON,
    corDestaque VARCHAR(9) DEFAULT '#000000',
    dataCriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    candidatos INT DEFAULT 0,
    status ENUM('ativo', 'inativo', 'encerrado') DEFAULT 'ativo',
    FOREIGN KEY (empresaID) REFERENCES users(userID) ON DELETE CASCADE,
    INDEX idx_area (area),
    INDEX idx_nivel (nivel),
    INDEX idx_tipoContrato (tipoContrato),
    INDEX idx_tipoTrabalho (tipoTrabalho),
    INDEX idx_localizacao (localizacao),
    INDEX idx_status (status),
    INDEX idx_dataCriacao (dataCriacao)
);