CREATE TABLE applications (
    candidaturaID INT AUTO_INCREMENT PRIMARY KEY,
    empregoID INT NOT NULL,
    userID INT NOT NULL,
    curriculoID INT NOT NULL,
    dataCandidatura TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM('pendente', 'em_analise', 'aprovado', 'rejeitado', 'cancelado') DEFAULT 'pendente',
    candidato_nome VARCHAR(255),
    candidato_email VARCHAR(255),
    candidato_telefone VARCHAR(20),
    candidato_localizacao VARCHAR(255),
    candidato_areaAtuacao VARCHAR(100),
    candidato_nivelExperiencia VARCHAR(50),
    candidato_linkedin VARCHAR(500),
    candidato_github VARCHAR(500),
    vaga_titulo VARCHAR(255),
    vaga_empresaNome VARCHAR(255),
    vaga_localizacao VARCHAR(255),
    vaga_area VARCHAR(100),
    FOREIGN KEY (empregoID) REFERENCES jobs(empregoID) ON DELETE CASCADE,
    FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE,
    FOREIGN KEY (curriculoID) REFERENCES resumes(curriculoID) ON DELETE CASCADE,
    UNIQUE KEY unique_candidatura (userID, empregoID),
    INDEX idx_empregoID (empregoID),
    INDEX idx_userID (userID),
    INDEX idx_status (status),
    INDEX idx_dataCandidatura (dataCandidatura)
);